// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discounts.proto

package discounts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscountRequest struct {
	Idprod               string   `protobuf:"bytes,1,opt,name=idprod,proto3" json:"idprod,omitempty"`
	Iduser               string   `protobuf:"bytes,2,opt,name=iduser,proto3" json:"iduser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountRequest) Reset()         { *m = DiscountRequest{} }
func (m *DiscountRequest) String() string { return proto.CompactTextString(m) }
func (*DiscountRequest) ProtoMessage()    {}
func (*DiscountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d8797b209114d25, []int{0}
}

func (m *DiscountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountRequest.Unmarshal(m, b)
}
func (m *DiscountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountRequest.Marshal(b, m, deterministic)
}
func (m *DiscountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountRequest.Merge(m, src)
}
func (m *DiscountRequest) XXX_Size() int {
	return xxx_messageInfo_DiscountRequest.Size(m)
}
func (m *DiscountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountRequest proto.InternalMessageInfo

func (m *DiscountRequest) GetIdprod() string {
	if m != nil {
		return m.Idprod
	}
	return ""
}

func (m *DiscountRequest) GetIduser() string {
	if m != nil {
		return m.Iduser
	}
	return ""
}

type DiscountReply struct {
	Pct                  float32  `protobuf:"fixed32,1,opt,name=pct,proto3" json:"pct,omitempty"`
	ValueInCents         int32    `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountReply) Reset()         { *m = DiscountReply{} }
func (m *DiscountReply) String() string { return proto.CompactTextString(m) }
func (*DiscountReply) ProtoMessage()    {}
func (*DiscountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d8797b209114d25, []int{1}
}

func (m *DiscountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountReply.Unmarshal(m, b)
}
func (m *DiscountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountReply.Marshal(b, m, deterministic)
}
func (m *DiscountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountReply.Merge(m, src)
}
func (m *DiscountReply) XXX_Size() int {
	return xxx_messageInfo_DiscountReply.Size(m)
}
func (m *DiscountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountReply.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountReply proto.InternalMessageInfo

func (m *DiscountReply) GetPct() float32 {
	if m != nil {
		return m.Pct
	}
	return 0
}

func (m *DiscountReply) GetValueInCents() int32 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

func init() {
	proto.RegisterType((*DiscountRequest)(nil), "discounts.DiscountRequest")
	proto.RegisterType((*DiscountReply)(nil), "discounts.DiscountReply")
}

func init() { proto.RegisterFile("discounts.proto", fileDescriptor_4d8797b209114d25) }

var fileDescriptor_4d8797b209114d25 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x39, 0x72, 0xf1, 0xbb, 0x40, 0x39, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x62, 0x5c,
	0x6c, 0x99, 0x29, 0x05, 0x45, 0xf9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x1e,
	0x44, 0xbc, 0xb4, 0x38, 0xb5, 0x48, 0x82, 0x09, 0x26, 0x0e, 0xe2, 0x29, 0xb9, 0x73, 0xf1, 0x22,
	0x8c, 0x28, 0xc8, 0xa9, 0x14, 0x12, 0xe0, 0x62, 0x2e, 0x48, 0x2e, 0x01, 0xeb, 0x66, 0x0a, 0x02,
	0x31, 0x85, 0x54, 0xb8, 0xf8, 0xca, 0x12, 0x73, 0x4a, 0x53, 0xe3, 0x33, 0xf3, 0xe2, 0x93, 0x53,
	0xf3, 0x4a, 0x8a, 0xc1, 0x46, 0xb0, 0x06, 0xf1, 0x80, 0x45, 0x3d, 0xf3, 0x9c, 0x41, 0x62, 0x46,
	0xfe, 0x5c, 0x9c, 0x30, 0x83, 0x8a, 0x85, 0x9c, 0xb8, 0x38, 0x60, 0x1c, 0x21, 0x29, 0x3d, 0x84,
	0x0f, 0xd0, 0x5c, 0x2b, 0x25, 0x81, 0x55, 0xae, 0x20, 0xa7, 0x52, 0x89, 0x21, 0x89, 0x0d, 0xec,
	0x5d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xb2, 0xad, 0xba, 0x01, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscountsClient is the client API for Discounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountsClient interface {
	Discount(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountReply, error)
}

type discountsClient struct {
	cc *grpc.ClientConn
}

func NewDiscountsClient(cc *grpc.ClientConn) DiscountsClient {
	return &discountsClient{cc}
}

func (c *discountsClient) Discount(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountReply, error) {
	out := new(DiscountReply)
	err := c.cc.Invoke(ctx, "/discounts.Discounts/Discount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountsServer is the server API for Discounts service.
type DiscountsServer interface {
	Discount(context.Context, *DiscountRequest) (*DiscountReply, error)
}

// UnimplementedDiscountsServer can be embedded to have forward compatible implementations.
type UnimplementedDiscountsServer struct {
}

func (*UnimplementedDiscountsServer) Discount(ctx context.Context, req *DiscountRequest) (*DiscountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discount not implemented")
}

func RegisterDiscountsServer(s *grpc.Server, srv DiscountsServer) {
	s.RegisterService(&_Discounts_serviceDesc, srv)
}

func _Discounts_Discount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountsServer).Discount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discounts.Discounts/Discount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountsServer).Discount(ctx, req.(*DiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discounts.Discounts",
	HandlerType: (*DiscountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discount",
			Handler:    _Discounts_Discount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discounts.proto",
}
