# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discounts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discounts.proto',
  package='discounts',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64iscounts.proto\x12\tdiscounts\"1\n\x0f\x44iscountRequest\x12\x0e\n\x06idprod\x18\x01 \x01(\t\x12\x0e\n\x06iduser\x18\x02 \x01(\t\"4\n\rDiscountReply\x12\x0b\n\x03pct\x18\x01 \x01(\x02\x12\x16\n\x0evalue_in_cents\x18\x02 \x01(\x05\x32O\n\tDiscounts\x12\x42\n\x08\x44iscount\x12\x1a.discounts.DiscountRequest\x1a\x18.discounts.DiscountReply\"\x00\x62\x06proto3')
)




_DISCOUNTREQUEST = _descriptor.Descriptor(
  name='DiscountRequest',
  full_name='discounts.DiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idprod', full_name='discounts.DiscountRequest.idprod', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iduser', full_name='discounts.DiscountRequest.iduser', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=79,
)


_DISCOUNTREPLY = _descriptor.Descriptor(
  name='DiscountReply',
  full_name='discounts.DiscountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pct', full_name='discounts.DiscountReply.pct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='discounts.DiscountReply.value_in_cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['DiscountRequest'] = _DISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['DiscountReply'] = _DISCOUNTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscountRequest = _reflection.GeneratedProtocolMessageType('DiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCOUNTREQUEST,
  '__module__' : 'discounts_pb2'
  # @@protoc_insertion_point(class_scope:discounts.DiscountRequest)
  })
_sym_db.RegisterMessage(DiscountRequest)

DiscountReply = _reflection.GeneratedProtocolMessageType('DiscountReply', (_message.Message,), {
  'DESCRIPTOR' : _DISCOUNTREPLY,
  '__module__' : 'discounts_pb2'
  # @@protoc_insertion_point(class_scope:discounts.DiscountReply)
  })
_sym_db.RegisterMessage(DiscountReply)



_DISCOUNTS = _descriptor.ServiceDescriptor(
  name='Discounts',
  full_name='discounts.Discounts',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='Discount',
    full_name='discounts.Discounts.Discount',
    index=0,
    containing_service=None,
    input_type=_DISCOUNTREQUEST,
    output_type=_DISCOUNTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNTS)

DESCRIPTOR.services_by_name['Discounts'] = _DISCOUNTS

# @@protoc_insertion_point(module_scope)
